project:
  type: book
  output-dir: _publish
  # render:
  #   - "*.qmd"
  #   - "!scratch/**"

book:
  title: "Introducción a los Modelos Probabilísticos (PSG-01M47)"
  subtitle: "Apuntes de Clase"
  author:
  - name: Alejandro Verri Kozlowski
    orcid: 0000-0002-8535-1170
    email: averri@fi.uba.ar
    attributes:
      corresponding: true
    affiliations:
      id: LABDIN/FIUBA
      name: Laboratorio de Dinámica de Estructuras
      department: Facultad de Ingeniería. Universidad de Buenos Aires (FIUBA)
      address: Las Heras 2214
      city: Ciudad de Buenos Aires
      country: Argentina
      postal_code: 1127
  language: es
  chapters:
    - index.qmd
    - _chapters/es/20250317.qmd
    - _chapters/es/20250321.qmd
    - _chapters/es/20250328.qmd
    - _chapters/es/20250331.qmd
    - _chapters/es/20250404.qmd
    - _chapters/es/20250414.qmd
    - _chapters/es/20250421.qmd
    - _chapters/es/20250425.qmd
    - _chapters/es/20250428.qmd
    - _chapters/es/20250512.qmd
    - _chapters/es/20250519.qmd
    - _chapters/es/20250523.qmd
    - _chapters/es/20250530.qmd
  # appendices:
  #   - references.qmd

format:
  html:
    theme:
      light: simplex # cosmo lumen litera lux materia minty morph pulse quartz sandstone simplex sketchy spacelab united yeti zephyr
      dark: cyborg # darkly cyborg slate solar superhero vapor
    highlight-style: a11y
    toc: true
    toc-location: right
    toc-title: "Contenidos"
    toc-depth: 3
    number-sections: true
    search: true
    page-navigation: true
    link-external-newwindow: true
    anchor-sections: true
    page-footer:
      left: |
        <span style="font-size:0.9em">© 2025 Alejandro Verri Kozlowski</span>
      right: |
        <span style="font-size:0.9em">Powered by <a href="https://quarto.org" target="_blank">Quarto</a></span>
    code-fold: true
    code-summary: "Source"
    code-line-numbers: false
    code-tools:
      source: true
      toggle: true
    code-overflow: scroll
    self-contained: false
    math: mathjax

  pdf:
    documentclass: scrreprt
    classoption: [oneside]
    geometry: ["margin=1.1in"]
    number-sections: true
